removed RPC-Async-V1-06 and extra check which is not required as part of CreateOperationAsyncResponseValidation
Azure/azure-openapi-validator pull request #527
Opened 2023-05-25 03:28 UTC by tejaswiMinnu

Removed - RPC-Async-V1-06 rule and its corresponding files and information.
 CreateOperationAsyncResponseValidation - has a false positive which has a check-> 'final-state-via' property set to 'azure-async-operation' 
Removed the check which is not required as the part of "CreateOperationAsyncResponseValidation" with this PR.

2023-05-25 14:18 UTC, visingla-ms approved these changes

2023-05-25 14:18 UTC, visingla-ms commented on docs/rules.md
> +### PropertiesTypeObjectNoDefinition
Sometimes also called "Free-form Objects", if we want to add this bit in description.

2023-05-30 22:33 UTC, rkmanda commented on packages/rulesets/src/native/legacyRules/CreateOperationAsyncResponseValidation.ts
>          }
remove this as well

2023-05-30 22:33 UTC, rkmanda requested changes
:clock1:

2023-06-01 20:23 UTC, bdefoy approved these changes

2023-06-01 21:51 UTC, rkmanda approved these changes
:shipit:

2023-06-01 21:53 UTC, merged