Added new rule LroAzureAsyncOperationHeader
Azure/azure-openapi-validator pull request #749
Opened 2024-10-14 22:14 UTC by tejaswiMinnu

LroAzureAsyncOperationHeader rule checks "Azure-AsyncOperation" header must be added for all async operations that response status code 202

[WorkItem](https://msazure.visualstudio.com/One/_workitems/edit/29424555)

2024-10-15 23:25 UTC, bdefoy commented on docs/lro-azure-async-operation-header.md
> +A 202 response should include an Azure-AsyncOperation response header.
```suggestion
A 202 response must include an Azure-AsyncOperation response header.
```

2024-10-16 18:17 UTC, rkmanda commented on packages/rulesets/src/spectral/az-arm.ts
> +      given: "$.paths[*][*].responses[?(@property == '202')]",
>s[?(@property == '202') [](http://example.com/codeflow?start=36&length=23)

This rule is actually for all long running operations. Not just for the 202 status code. Sorry I should have clarified this earlier.

2024-10-16 18:17 UTC, rkmanda requested changes
:clock1:

2025-02-25 01:19 UTC, tejaswiMinnu commented on docs/lro-azure-async-operation-header.md
> +A 202 response should include an Azure-AsyncOperation response header.
Updated

2025-02-25 01:21 UTC, tejaswiMinnu commented on packages/rulesets/src/spectral/az-arm.ts
> +      given: "$.paths[*][*].responses[?(@property == '202')]",
Modified the rule to address all LRO operations

2025-02-25 23:46 UTC, bdefoy commented on packages/rulesets/src/spectral/test/lro-azure-async-operation-header.test.ts
> +              // no header scenario
Should this cause an error? Since it's a long running operation and the rule is

> All long-running operations must include an Azure-AsyncOperation response header.

2025-02-25 23:51 UTC, tejaswiMinnu commented on packages/rulesets/src/spectral/test/lro-azure-async-operation-header.test.ts
> +              // no header scenario
It won't cause there is no headers property inside the response 202
This rule flags error if there is headers defined without Azure-AsyncOperation property

2025-02-27 16:29 UTC, AkhilaIlla commented
>       stagingOnly: true,

are we no longer doing 
stagingOnly: true
for new rules?

---
Refers to: packages/rulesets/src/spectral/az-arm.ts:341 in 032a1d2. [](commit_id = 032a1d2f867e0f1796fc61ed74d4da170604b91d, deletion_comment = False)

2025-02-27 18:27 UTC, tejaswiMinnu commented on packages/rulesets/src/spectral/test/lro-azure-async-operation-header.test.ts
> +              // no header scenario
Modified, Thanks Brett

2025-02-27 18:28 UTC, tejaswiMinnu commented on docs/lro-azure-async-operation-header.md
> +All long-running operations must include an Azure-AsyncOperation response header.
Modified

2025-02-27 19:49 UTC, rkmanda commented on docs/lro-azure-async-operation-header.md
> +
All long-running operations must include an `Azure-AsyncOperation` response header.

2025-02-27 19:54 UTC, rkmanda commented on packages/rulesets/src/spectral/az-arm.ts
> +      description: "All long-running operations that define the `headers` field must include an `Azure-AsyncOperation` response header.",
>All long-running operations that define the `headers` field must include an `Azure-AsyncOperation` response header. [](http://example.com/codeflow?start=20&length=115)

All long-running operations must include an `Azure-AsyncOperation` response header.

2025-02-27 19:55 UTC, rkmanda commented on packages/rulesets/src/spectral/az-arm.ts
> +        "$[paths,'x-ms-paths'].*.*[?(@property === 'x-ms-long-running-operation' && @ === true)]^.responses.*.headers[?(@property !== 'Azure-AsyncOperation')]",
>= true)]^.responses.*.headers[?(@property !== 'Azure-AsyncOperation')]", [](http://example.com/codeflow?start=88&length=72)

if header is field is missing, it should also be considered an error for this rule

2025-02-27 19:55 UTC, rkmanda commented on packages/rulesets/src/spectral/test/lro-azure-async-operation-header.test.ts
> +              // no header scenario
>    // no header scenario [](http://example.com/codeflow?start=10&length=25)

This must throw an error

2025-02-27 21:46 UTC, tejaswiMinnu commented on packages/rulesets/src/spectral/az-arm.ts
> +        "$[paths,'x-ms-paths'].*.*[?(@property === 'x-ms-long-running-operation' && @ === true)]^.responses.*.headers[?(@property !== 'Azure-AsyncOperation')]",
Oh no, initially I thought that and I asked you about this in one of the scrums for confirmation about the header. Maybe I didn't phrase it well or confused you.

2025-02-28 00:39 UTC, tejaswiMinnu commented on packages/rulesets/src/spectral/test/lro-azure-async-operation-header.test.ts
> +              // no header scenario
Added new function

2025-02-28 00:39 UTC, tejaswiMinnu commented on packages/rulesets/src/spectral/az-arm.ts
> +      description: "All long-running operations that define the `headers` field must include an `Azure-AsyncOperation` response header.",
Changed back

2025-02-28 00:39 UTC, tejaswiMinnu commented on docs/lro-azure-async-operation-header.md
> +all asynchronous long-running operations.
Updated

2025-02-28 00:40 UTC, tejaswiMinnu commented on docs/lro-azure-async-operation-header.md
> +
changed back

2025-02-28 16:07 UTC, bdefoy commented on packages/rulesets/src/spectral/az-arm.ts
> +      given: ["$[paths,'x-ms-paths'].*.*[?(@property === 'x-ms-long-running-operation' && @ === true)]^.responses.*.headers"],
I believe this will only pass in the headers object if it exists. If it does not, it will not call the function. I think you would need to make the given part like this
```suggestion
      given: ["$[paths,'x-ms-paths'].*.*[?(@property === 'x-ms-long-running-operation' && @ === true)]^.responses.*.*"],
```

2025-02-28 16:07 UTC, bdefoy commented on packages/rulesets/src/spectral/az-arm.ts
> +      description: "All long-running operations must include an `Azure-AsyncOperation' response header.",
```suggestion
      description: "All long-running operations must include an `Azure-AsyncOperation` response header.",
```

2025-02-28 16:07 UTC, bdefoy commented on packages/rulesets/src/spectral/functions/lro-azure-async-operation-header.ts
> +          message: "All long-running operations must include an `Azure-AsyncOperation' response header.",
```suggestion
          message: "All long-running operations must include an `Azure-AsyncOperation` response header.",
```

2025-02-28 16:07 UTC, bdefoy commented on packages/rulesets/src/spectral/test/lro-azure-async-operation-header.test.ts
> +const ERROR_MESSAGE = "All long-running operations must include an `Azure-AsyncOperation' response header."
```suggestion
const ERROR_MESSAGE = "All long-running operations must include an `Azure-AsyncOperation` response header."
```

2025-02-28 16:07 UTC, bdefoy commented on packages/rulesets/generated/spectral/az-arm.js
> +            description: "All long-running operations must include an `Azure-AsyncOperation' response header.",
```suggestion
            description: "All long-running operations must include an `Azure-AsyncOperation` response header.",
```

2025-02-28 16:07 UTC, bdefoy commented on packages/rulesets/generated/spectral/az-arm.js
> +                    message: "All long-running operations must include an `Azure-AsyncOperation' response header.",
```suggestion
                    message: "All long-running operations must include an `Azure-AsyncOperation` response header.",
```

2025-02-28 16:07 UTC, bdefoy commented on packages/rulesets/src/spectral/test/lro-azure-async-operation-header.test.ts
> +              description: "No header case",
This case should error so there should be
<pre>
expect(results[0].path.join(".")).toBe("paths./foo1/operations.<b>post</b>.responses.202.headers")
</pre>
in the assertions

2025-02-28 18:55 UTC, tejaswiMinnu commented on packages/rulesets/src/spectral/az-arm.ts
> +      given: ["$[paths,'x-ms-paths'].*.*[?(@property === 'x-ms-long-running-operation' && @ === true)]^.responses.*.headers"],
*.* is also skipping the headers check, have to tweak some code changes in lro-azure-async-operation-header.ts file

2025-02-28 18:55 UTC, tejaswiMinnu commented on packages/rulesets/src/spectral/az-arm.ts
> +      description: "All long-running operations must include an `Azure-AsyncOperation' response header.",
Modified all files

2025-02-28 19:35 UTC, bdefoy approved these changes

2025-02-28 21:11 UTC, AkhilaIlla commented on docs/lro-azure-async-operation-header.md
> +Adding the Azure-AsyncOperation header to the response..
>. [](http://example.com/codeflow?start=55&length=1)

nit: extra

2025-03-03 17:29 UTC, tejaswiMinnu commented on docs/lro-azure-async-operation-header.md
> +Adding the Azure-AsyncOperation header to the response..
Removed

2025-03-03 17:45 UTC, AkhilaIlla commented on docs/lro-azure-async-operation-header.md
> +and the status of the resource. If you are a brownfield service that does not implement this header, you may add a
>brownfield [](http://example.com/codeflow?start=45&length=10)

what is a brownfieldservice?

2025-03-03 17:53 UTC, AkhilaIlla commented on docs/lro-azure-async-operation-header.md
> +## Good Example
can we also add the example without "Azure-AsyncOperation" id also good if `"headers"` filed is not present.

2025-03-03 17:59 UTC, AkhilaIlla commented on docs/lro-azure-async-operation-header.md
> +## Good Example
Looked at the logic update, can we add the opposite to the bad examples please?

2025-03-03 17:59 UTC, AkhilaIlla approved these changes

2025-03-03 18:15 UTC, tejaswiMinnu commented on docs/lro-azure-async-operation-header.md
> +and the status of the resource. If you are a brownfield service that does not implement this header, you may add a
All the existing service's refers to brownfield services

2025-03-10 18:23 UTC, rkmanda commented on docs/lro-azure-async-operation-header.md
> +and the status of the resource. If you are a brownfield service that does not implement this header, you may add a
maybe just mention it in brackets (existing service with atleast one stable API version shipped to customer)

2025-03-10 19:16 UTC, merged